main: radWorld.Main
name: RadWorld
version: 0.4-Dev
api-version: 1.17
author: Platratio34
commands:
  rads:
    usage: /rads player <add|remove|level|set|enabled> [player] {arg} | /rads global <damage|recovery|radMultip> [value] | /rads disable <true|false> | /rads version | /rads reload
    descrition: The primary command for interacting with RadWorld
